name: Just a POC Manual Integration Tests - Staging

on:
  workflow_dispatch:

jobs:
  integration_tests_staging:
    name: "Deploy & Test in Staging"
    runs-on: ubuntu-latest
    # Using the staging environment for Service Principal secrets
    environment: staging
    
    env:
      # Assume the DAB bundle is already initialized in the repo but this step would actually come after dab deployment unless it can be run against the file directory
      # Using Staging Service Principal credentials from Git Secrets/Vars
      # using staging here because i havent set up env vars in git for dev yet
      DATABRICKS_HOST: ${{ vars.DBX_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DBX_SP_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DBX_SP_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      # this step would come after dab deploy? or would run first dev dab?
      # i dont want a fail really and the code to be sat there known to be bad so running locally via a hook could be good pre-push?
      # The notebook will actually run both as set up atm but maybe its ok for now
      # shouldnt have named the job and the yml file the same oops
      - name: Run Integration Tests
        run: |
          echo "running the integration yml test job integration_test_job.yml"
          databricks bundle run -t staging integration_test_job
