name: Prod PR Checks

on:
  pull_request:
    branches:
      - main
      # Trigger on PRs targeting the dev branch

jobs:
  validate-prod:
    name: Validate prod
    runs-on: ubuntu-latest
    environment: prod
    env:
      DATABRICKS_HOST: ${{ vars.DBX_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DBX_SP_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DBX_SP_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Prod Target
        run: databricks bundle validate -t prod
    
  check-staging-is-stable:
    name: Check staging still stable before deploy to prod
    runs-on: ubuntu-latest
    environment: staging
    env:
      DATABRICKS_HOST: ${{ vars.DBX_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DBX_SP_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DBX_SP_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

        # The notebook will actually run both as set up atm but maybe its ok for now
      - name: Check Staging Integration Tests Before Allowing Prod Deploy
        run: |
          echo "running the integration yml test job integration_test_job.yml"
          databricks bundle run -t staging integration_test_job

