name: Staging PR Checks

on:
  pull_request:
    branches:
      - staging-data-test-team-shared  # Trigger on PRs targeting the dev branch

jobs:
  validate-staging:
    name: Validate staging
    runs-on: ubuntu-latest
    environment: staging
    env:
      DATABRICKS_HOST: ${{ vars.DBX_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DBX_SP_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DBX_SP_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Staging Target
        run: databricks bundle validate -t staging

    check-dev-is-stable:
      name: Check dev still stable before deploy to staging
      runs-on: ubuntu-latest
      environment: dev
      env:
        DATABRICKS_HOST: ${{ vars.DBX_HOST }}
        DATABRICKS_CLIENT_ID: ${{ vars.DBX_SP_ID }}
        DATABRICKS_CLIENT_SECRET: ${{ secrets.DBX_SP_SECRET }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Databricks CLI
          uses: databricks/setup-cli@main

        # The notebook will actually run both as set up atm but maybe its ok for now
        - name: Check Dev Integration Tests Before Allowing Sing Deploy
          run: |
            echo "running the integration yml test job integration_test_job.yml"
            databricks bundle run -t dev run_integration_tests