# Rely on ci.yml and branch rules to ensure bundle validation and linting
# we are not going from staging straight to prod, because we use staging for manual testing as well
# [use as a ref](https://github.com/evanaze/dbx-asset-bundle-deployment/blob/main/.github/workflows/dev-ci.yml)
name: Deploy to Databricks Staging and Trigger Tests in Databricks

on:
  push:
    branches:
      - staging #longer name for communication in the poc reduce when using it
      - staging-data-test-team-shared

jobs:
  deploy_to_staging:
    name: "Deploy Bundle to Stage Environment"
    runs-on: ubuntu-latest
    environment: staging
    env:
      DATABRICKS_HOST: ${{ vars.DBX_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DBX_SP_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DBX_SP_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Staging Bundle
      # trigger target the staging deploy in databricks.yml
        run: databricks bundle validate -t staging #--profile ""  # forces use of env vars only # didnt work

      - name: Deploy Staging Bundle
      # trigger target the staging deploy in databricks.yml
        run: databricks bundle deploy -t staging #--profile ""  # forces use of env vars only #??--auto-approve # didnt work
       # working-directory: .

##### Probably need as a linear job to ensure that setup has happened or some wait but then this has worked from the manual side

      # this step would come after dab deploy? or would run first dev dab?
      # i dont want a fail really and the code to be sat there known to be bad so running locally via a hook could be good pre-push?
      # The notebook will actually run both as set up atm but maybe its ok for now
      # shouldnt have named the job and the yml file the same oops
      #- name: Run Integration Tests
      #  run: |
      #    echo "running the integration yml test job integration_test_job.yml"
      #    databricks bundle run -t staging integration_test_job
